---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  replicas: 5
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      # whenUnsatisfiable: <string>
      # labelSelector: <object>
  template:
    spec:
      containers:
        - name: podinfod
          env:
            - name: PODINFO_UI_COLOR
              value: "#420D09"
