---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-apps
  namespace: fysicon-bartb
spec:
  interval: 10m0s
  path: ./exercises/helm-controller/staging
  prune: true
  serviceAccountName: flux-reconciler
  sourceRef:
    kind: GitRepository
    name: flux-fundamentals

