---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: cluster
    kustomize.toolkit.fluxcd.io/namespace: fysicon-bartb
  name: cluster
  namespace: fysicon-bartb
spec:
  interval: 10m0s
  path: ./cluster/staging
  prune: false
  serviceAccountName: flux-reconciler
  sourceRef:
    kind: GitRepository
    name: flux-fundamentals

